### ISSUE TITLE
Question: query_count

### ISSUE THREAD

**Issue by bdmorin** [BlueMedora/new-relic-plugins#7]
In the config file:
"query_count": "your_value_here",

What is this? I don't see it in the documentation.

**Comment by bluemedorasupport** [comment]
Hi (sorry, don't have your name), 
   
 The query count metric is the number of queries that the plugin pulls back from whatever database you are trying to monitor.  So, New Relic will bring back your top TEN slowest queries is TEN is the number you put into your query count.  This is usually the default that we stick with, but if you wanted your top fifteen, or top twenty, you could put that number into your query count. 
   
 I hope that answers your question.  If you would like to get on a call with one of our Solutions Architects, we can always set up a quick call so you can ask any further questions.  Of course you can always email me directly as well.  My contact information is below. 
   
 Cheers, 
   
 Tim George 
 Customer Success Manager 
 Blue Medora 
 616-426-3792 
   
   
   
   
   
   
  
   
 
 
 
                 
         On Thu, 27 Oct at  4:26 PM
          ,  BlueMedora/new-relic-plugins <reply@reply.github.com>  wrote:
           In the config file: 
"query_count": "your_value_here", 

 What is this? I don't see it in the documentation.

**Comment by vvchik** [comment]
It should be reflected in documentation

**Comment by bdmorin** [comment]
Thank you so much! Appreciate your plugin, it's proving useful for us.

**Comment by bluemedorasupport** [comment]
Hi , 
   
 I am glad you were able to get everything working for you.  We usually like to set up a review call and make sure the plugin is collecting all the data that you were looking for.  Do you have time this week to jump on a call with Blue Medora's New Relic team to discuss? 
   
 Cheers, 
   
 Tim George 
 Customer Success Manager 
 Blue Medora 
 616-426-3792 
   
  
   
 
 
 
                 
         On Fri, 28 Oct at  8:39 AM
          ,  Blue Medora Support <support@bluemedora.com>  wrote:
           
 
 
 Hi (sorry, don't have your name), 
   
 The query count metric is the number of queries that the plugin pulls back from whatever database you are trying to monitor.  So, New Relic will bring back your top TEN slowest queries is TEN is the number you put into your query count.  This is usually the default that we stick with, but if you wanted your top fifteen, or top twenty, you could put that number into your query count. 
   
 I hope that answers your question.  If you would like to get on a call with one of our Solutions Architects, we can always set up a quick call so you can ask any further questions.  Of course you can always email me directly as well.  My contact information is below. 
   
 Cheers, 
   
 Tim George 
 Customer Success Manager 
 Blue Medora 
 616-426-3792 
   
   
   
   
   
   
  
   
 
 
 
                 
         On Thu, 27 Oct at  4:26 PM
          ,  BlueMedora/new-relic-plugins <reply@reply.github.com>  wrote:
           In the config file: 
"query_count": "your_value_here", 

 What is this? I don't see it in the documentation.

**Comment by bluemedorasupport** [comment]
Hi, 
   
 I didn't hear back from you after my last email so I wanted to send a quick email and see how the trial of our plugin went.  Did you get all the information back that you were looking for?  Was it useful at all?  Is there a good time we can get on a call to go over some of your feedback and discuss next steps, if any? 
   
 Cheers, 
   
 Tim George 
   
   
  
   
 
 
 
                 
         On Mon, 31 Oct at 12:09 PM
          ,  Blue Medora Support <support@bluemedora.com>  wrote:
           
 
 
 Hi ,
 
   
 I am glad you were able to get everything working for you.  We usually like to set up a review call and make sure the plugin is collecting all the data that you were looking for.  Do you have time this week to jump on a call with Blue Medora's New Relic team to discuss? 
   
 Cheers, 
   
 Tim George 
 Customer Success Manager 
 Blue Medora 
 616-426-3792 
   
  
   
 
 
 
                 
         On Fri, 28 Oct at  8:39 AM
          ,  Blue Medora Support <support@bluemedora.com>  wrote:
           
 
 
 Hi (sorry, don't have your name), 
   
 The query count metric is the number of queries that the plugin pulls back from whatever database you are trying to monitor.  So, New Relic will bring back your top TEN slowest queries is TEN is the number you put into your query count.  This is usually the default that we stick with, but if you wanted your top fifteen, or top twenty, you could put that number into your query count. 
   
 I hope that answers your question.  If you would like to get on a call with one of our Solutions Architects, we can always set up a quick call so you can ask any further questions.  Of course you can always email me directly as well.  My contact information is below. 
   
 Cheers, 
   
 Tim George 
 Customer Success Manager 
 Blue Medora 
 616-426-3792 
   
   
   
   
   
   
  
   
 
 
 
                 
         On Thu, 27 Oct at  4:26 PM
          ,  BlueMedora/new-relic-plugins <reply@reply.github.com>  wrote:
           In the config file: 
"query_count": "your_value_here", 

 What is this? I don't see it in the documentation.

**Comment by bluemedorasupport** [comment]
Hi , 
   
 I wanted to send a quick email to see if you were still interested in our plugin for New Relic.  Are you still looking to evaluate? 
   
 Cheers, 
 Tim 
   
   
  
   
 
 
 
                 
         On Wed, 30 Nov, 2016 at  4:30 PM
          ,  Blue Medora Support <support@bluemedora.com>  wrote:
           
 
 
 Hi,
 
   
 I didn't hear back from you after my last email so I wanted to send a quick email and see how the trial of our plugin went.  Did you get all the information back that you were looking for?  Was it useful at all?  Is there a good time we can get on a call to go over some of your feedback and discuss next steps, if any? 
   
 Cheers, 
   
 Tim George 
   
   
  
   
 
 
 
                 
         On Mon, 31 Oct at 12:09 PM
          ,  Blue Medora Support <support@bluemedora.com>  wrote:
           
 
 
 Hi ,
 
   
 I am glad you were able to get everything working for you.  We usually like to set up a review call and make sure the plugin is collecting all the data that you were looking for.  Do you have time this week to jump on a call with Blue Medora's New Relic team to discuss? 
   
 Cheers, 
   
 Tim George 
 Customer Success Manager 
 Blue Medora 
 616-426-3792 
   
  
   
 
 
 
                 
         On Fri, 28 Oct at  8:39 AM
          ,  Blue Medora Support <support@bluemedora.com>  wrote:
           
 
 
 Hi (sorry, don't have your name), 
   
 The query count metric is the number of queries that the plugin pulls back from whatever database you are trying to monitor.  So, New Relic will bring back your top TEN slowest queries is TEN is the number you put into your query count.  This is usually the default that we stick with, but if you wanted your top fifteen, or top twenty, you could put that number into your query count. 
   
 I hope that answers your question.  If you would like to get on a call with one of our Solutions Architects, we can always set up a quick call so you can ask any further questions.  Of course you can always email me directly as well.  My contact information is below. 
   
 Cheers, 
   
 Tim George 
 Customer Success Manager 
 Blue Medora 
 616-426-3792 
   
   
   
   
   
   
  
   
 
 
 
                 
         On Thu, 27 Oct at  4:26 PM
          ,  BlueMedora/new-relic-plugins <reply@reply.github.com>  wrote:
           In the config file: 
"query_count": "your_value_here", 

 What is this? I don't see it in the documentation.
